<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;


class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('productos')->insert(['nombre_producto'=>'Laptop gamer','descripcion'=>'Cuadro de picaso, lo tengo porque soy familiar de picaso 100% seguro, fijense en las imagenes','precio_inicial'=>30.2,'image_name1'=>'http://imgfz.com/i/ghJeXZQ.jpeg','image_name2'=>'http://imgfz.com/i/ghJeXZQ.jpeg','image_name3'=>'http://imgfz.com/i/ghJeXZQ.jpeg','image_name4'=>'http://imgfz.com/i/ghJeXZQ.jpeg','estado'=>'Disponible','inicio_subasta'=>'2020-11-25 18:47:00','final_subasta'=>'2020-12-16 23:47:00','user_id'=>1,'latitud'=>-6.770989,'longitud'=>-79.853396,'categoria_id'=>1,'user_id_comprador'=>2,'condicion'=>'Nuevo','ubicacion'=>'Lambayeque','distrito'=>'Chiclayo','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Puerta de oro','descripcion'=>'Maso hecho de oro 100% oro','precio_inicial'=>90.0,'image_name1'=>'http://imgfz.com/i/6baLGPT.jpeg','image_name2'=>'http://imgfz.com/i/6baLGPT.jpeg','image_name3'=>'http://imgfz.com/i/6baLGPT.jpeg','image_name4'=>'http://imgfz.com/i/6baLGPT.jpeg','estado'=>'No disponible','user_id'=>1,'categoria_id'=>1,'user_id_comprador'=>2,'latitud'=>-6.770989,'longitud'=>-79.853396,'condicion'=>'Usado','ubicacion'=>'Lambayeque','distrito'=>'Chiclayo','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Estatua cervantes','descripcion'=>'Libro original de Servantes, lo vendo porque necesito espacio en mi casa','precio_inicial'=>100.2,'image_name1'=>'http://imgfz.com/i/uGhDcmr.jpeg','image_name2'=>'http://imgfz.com/i/uGhDcmr.jpeg','image_name3'=>'http://imgfz.com/i/uGhDcmr.jpeg','image_name4'=>'http://imgfz.com/i/uGhDcmr.jpeg','estado'=>'Disponible','inicio_subasta'=>'2020-11-25 20:47:00','final_subasta'=>'2021-12-14 22:47:00','user_id'=>2,'categoria_id'=>2,'user_id_comprador'=>2,'latitud'=>-6.770989,'longitud'=>-79.853396,'condicion'=>'Nuevo','ubicacion'=>'Lambayeque','distrito'=>'Chiclayo','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Monalisa','descripcion'=>'Cuadro de picaso, lo tengo porque soy familiar de picaso 100% seguro, fijense en las imagenes','precio_inicial'=>30.2,'image_name1'=>'http://imgfz.com/i/WVCnYNe.jpeg','image_name2'=>'http://imgfz.com/i/WVCnYNe.jpeg','image_name3'=>'http://imgfz.com/i/WVCnYNe.jpeg','image_name4'=>'http://imgfz.com/i/WVCnYNe.jpeg','estado'=>'En curso','inicio_subasta'=>'2020-12-10 20:47:00','final_subasta'=>'2021-12-18 18:30:00','user_id'=>1,'categoria_id'=>2,'latitud'=>-12.0621065,'longitud'=>-77.0365256,'user_id_comprador'=>2,'condicion'=>'Nuevo','ubicacion'=>'Lambayeque','distrito'=>'Chiclayo','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Requilia antigua','descripcion'=>'Maso hecho de oro 100% oro','precio_inicial'=>800.0,'image_name1'=>'http://imgfz.com/i/g7Alfst.jpeg','image_name2'=>'http://imgfz.com/i/g7Alfst.jpeg','image_name3'=>'http://imgfz.com/i/g7Alfst.jpeg','image_name4'=>'http://imgfz.com/i/g7Alfst.jpeg','estado'=>'En curso','inicio_subasta'=>'2020-12-12 20:47:00','final_subasta'=>'2021-12-27 20:55:00','user_id'=>1,'categoria_id'=>3,'user_id_comprador'=>2,'latitud'=>-12.59254,'longitud'=>-69.188191,'condicion'=>'Nuevo','ubicacion'=>'Lambayeque','distrito'=>'Chiclayo','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Libro de llosa','descripcion'=>'Libro original de Llosa, lo vendo porque necesito espacio en mi casa','precio_inicial'=>100.2,'image_name1'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name2'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name3'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name4'=>'http://imgfz.com/i/bEdwRlf.jpeg','estado'=>'En curso','inicio_subasta'=>'2020-11-21 20:47:20','final_subasta'=>'2021-12-20 20:17:10','user_id'=>2,'categoria_id'=>3,'latitud'=>-5.195464,'longitud'=>-80.630873,'user_id_comprador'=>2,'condicion'=>'Usado','ubicacion'=>'Lambayeque','distrito'=>'Chiclayo','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Perlas','descripcion'=>'perlas hecho de oro 100% perlas','precio_inicial'=>300.0,'image_name1'=>'http://imgfz.com/i/vrnLG64.jpeg','image_name2'=>'http://imgfz.com/i/vrnLG64.jpeg','image_name3'=>'http://imgfz.com/i/vrnLG64.jpeg','image_name4'=>'http://imgfz.com/i/vrnLG64.jpeg','estado'=>'En curso','inicio_subasta'=>'2020-12-10 20:47:00','final_subasta'=>'2021-12-17 20:33:00','user_id'=>1,'categoria_id'=>4,'user_id_comprador'=>3,'user_id_comprador'=>2,'latitud'=>-18.0138521,'longitud'=>-70.2511614,'condicion'=>'Nuevo','ubicacion'=>'Lambayeque','distrito'=>'Chiclayo','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Libro de cocina','descripcion'=>'Libro de cocina, lo vendo porque necesito espacio en mi casa','precio_inicial'=>100.2,'image_name1'=>'http://imgfz.com/i/Qvz10x7.png','image_name2'=>'http://imgfz.com/i/Qvz10x7.png','image_name3'=>'http://imgfz.com/i/Qvz10x7.png','image_name4'=>'http://imgfz.com/i/Qvz10x7.png','estado'=>'En curso','inicio_subasta'=>'2020-11-27 21:30:00','final_subasta'=>'2021-12-15 20:47:00','user_id'=>2,'categoria_id'=>4,'latitud'=>-3.565364,'longitud'=>-80.456874,'user_id_comprador'=>2,'condicion'=>'Nuevo','ubicacion'=>'Lambayeque','distrito'=>'Chiclayo','garantia'=>'No tiene garantía']);
        //Historial
        DB::table('productos')->insert(['nombre_producto'=>'Cuadro de Da vinci','descripcion'=>'Cuadro de Da vinci, lo tengo porque soy familiar de Da vinci 100% seguro, fijense en las imagenes','precio_inicial'=>30.2,'image_name1'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name2'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name3'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name4'=>'http://imgfz.com/i/bEdwRlf.jpeg','estado'=>'Comprado','inicio_subasta'=>'2020-12-25 20:47:00','final_subasta'=>'2021-12-13 20:47:00','user_id'=>1,'latitud'=>-8.383393,'longitud'=>-74.538623,'categoria_id'=>5,'user_id_comprador'=>2,'condicion'=>'Usado','ubicacion'=>'Lambayeque','distrito'=>'Chiclayo','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Mazo de platano','descripcion'=>'Maso hecho de platano 100% oro','precio_inicial'=>90.0,'image_name1'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name2'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name3'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name4'=>'http://imgfz.com/i/bEdwRlf.jpeg','estado'=>'Comprado','inicio_subasta'=>'2020-11-20 10:17:00','final_subasta'=>'2021-12-20 20:47:00','user_id'=>1,'categoria_id'=>5,'user_id_comprador'=>2,'condicion'=>'Nuevo','latitud'=>-12.59254,'longitud'=>-69.188191,'ubicacion'=>'Lambayeque','distrito'=>'Chiclayo','garantia'=>'No tiene garantía']);


        DB::table('productos')->insert(['nombre_producto'=>'Cuadro de picaso','descripcion'=>'Cuadro de picaso, lo tengo porque soy familiar de picaso 100% seguro, fijense en las imagenes','precio_inicial'=>30.2,'image_name1'=>'http://imgfz.com/i/ghJeXZQ.jpeg','image_name2'=>'http://imgfz.com/i/ghJeXZQ.jpeg','image_name3'=>'http://imgfz.com/i/ghJeXZQ.jpeg','image_name4'=>'http://imgfz.com/i/ghJeXZQ.jpeg','estado'=>'Disponible','inicio_subasta'=>'2020-11-25 18:47:00','final_subasta'=>'2021-12-15 23:47:00','user_id'=>1,'latitud'=>-6.770989,'longitud'=>-79.843396,'categoria_id'=>1,'user_id_comprador'=>2,'condicion'=>'Nuevo','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Mazo de oro 1996','descripcion'=>'Maso hecho de oro 100% oro','precio_inicial'=>90.0,'image_name1'=>'http://imgfz.com/i/6baLGPT.jpeg','image_name2'=>'http://imgfz.com/i/6baLGPT.jpeg','image_name3'=>'http://imgfz.com/i/6baLGPT.jpeg','image_name4'=>'http://imgfz.com/i/6baLGPT.jpeg','estado'=>'No disponible','user_id'=>1,'categoria_id'=>1,'latitud'=>-14.06493,'longitud'=>-75.728827,'user_id_comprador'=>2,'condicion'=>'Nuevo','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Libro de servantes(original)','descripcion'=>'Libro original de Servantes, lo vendo porque necesito espacio en mi casa','precio_inicial'=>100.2,'image_name1'=>'http://imgfz.com/i/uGhDcmr.jpeg','image_name2'=>'http://imgfz.com/i/uGhDcmr.jpeg','image_name3'=>'http://imgfz.com/i/uGhDcmr.jpeg','image_name4'=>'http://imgfz.com/i/uGhDcmr.jpeg','estado'=>'Disponible','inicio_subasta'=>'2020-11-25 20:47:00','final_subasta'=>'2021-12-14 22:47:00','user_id'=>2,'latitud'=>-7.158863,'longitud'=>-78.516059,'categoria_id'=>2,'user_id_comprador'=>2,'condicion'=>'Nuevo','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Cuadro de picaso','descripcion'=>'Cuadro de picaso, lo tengo porque soy familiar de picaso 100% seguro, fijense en las imagenes','precio_inicial'=>30.2,'image_name1'=>'http://imgfz.com/i/WVCnYNe.jpeg','image_name2'=>'http://imgfz.com/i/WVCnYNe.jpeg','image_name3'=>'http://imgfz.com/i/WVCnYNe.jpeg','image_name4'=>'http://imgfz.com/i/WVCnYNe.jpeg','estado'=>'En curso','inicio_subasta'=>'2020-12-10 20:47:00','final_subasta'=>'2021-12-30 18:30:00','user_id'=>1,'latitud'=>-9.529993,'longitud'=>-77.531704,'categoria_id'=>2,'user_id_comprador'=>2,'condicion'=>'Usado','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Mazo de oro 1996','descripcion'=>'Maso hecho de oro 100% oro','precio_inicial'=>800.0,'image_name1'=>'http://imgfz.com/i/g7Alfst.jpeg','image_name2'=>'http://imgfz.com/i/g7Alfst.jpeg','image_name3'=>'http://imgfz.com/i/g7Alfst.jpeg','image_name4'=>'http://imgfz.com/i/g7Alfst.jpeg','estado'=>'En curso','inicio_subasta'=>'2020-12-22 20:47:00','final_subasta'=>'2021-12-27 20:55:00','user_id'=>1,'categoria_id'=>3,'user_id_comprador'=>2,'condicion'=>'Nuevo','ubicacion'=>'Lima','latitud'=>-6.230835,'longitud'=>-77.871217,'distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Libro de servantes(original)','descripcion'=>'Libro original de Servantes, lo vendo porque necesito espacio en mi casa','precio_inicial'=>100.2,'image_name1'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name2'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name3'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name4'=>'http://imgfz.com/i/bEdwRlf.jpeg','estado'=>'En curso','inicio_subasta'=>'2020-11-21 20:47:20','final_subasta'=>'2021-12-29 20:17:10','user_id'=>2,'latitud'=>-13.161174,'longitud'=>-74.225245,'categoria_id'=>3,'user_id_comprador'=>2,'condicion'=>'Nuevo','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Mazo de oro 1996','descripcion'=>'Maso hecho de oro 100% oro','precio_inicial'=>300.0,'image_name1'=>'http://imgfz.com/i/vrnLG64.jpeg','image_name2'=>'http://imgfz.com/i/vrnLG64.jpeg','image_name3'=>'http://imgfz.com/i/vrnLG64.jpeg','image_name4'=>'http://imgfz.com/i/vrnLG64.jpeg','estado'=>'En curso','inicio_subasta'=>'2020-12-10 20:47:00','final_subasta'=>'2021-12-15 20:33:00','user_id'=>1,'categoria_id'=>4,'user_id_comprador'=>3,'user_id_comprador'=>2,'latitud'=>-13.522511,'longitud'=>-71.970643,'condicion'=>'Nuevo','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Libro de servantes(original)','descripcion'=>'Libro original de Servantes, lo vendo porque necesito espacio en mi casa','precio_inicial'=>100.2,'image_name1'=>'http://imgfz.com/i/Qvz10x7.png','image_name2'=>'http://imgfz.com/i/Qvz10x7.png','image_name3'=>'http://imgfz.com/i/Qvz10x7.png','image_name4'=>'http://imgfz.com/i/Qvz10x7.png','estado'=>'En curso','inicio_subasta'=>'2020-11-27 20:30:00','final_subasta'=>'2021-11-30 20:47:00','user_id'=>2,'latitud'=>-14.06493,'longitud'=>-75.728827,'categoria_id'=>4,'user_id_comprador'=>2,'condicion'=>'Usado','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);
        //Historial

        DB::table('productos')->insert(['nombre_producto'=>'Cuadro de baseloti','descripcion'=>'Cuadro de picaso, lo tengo porque soy familiar de picaso 100% seguro, fijense en las imagenes','precio_inicial'=>30.2,'image_name1'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name2'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name3'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name4'=>'http://imgfz.com/i/bEdwRlf.jpeg','estado'=>'Comprado','inicio_subasta'=>'2020-12-25 20:47:00','final_subasta'=>'2021-12-30 20:47:00','user_id'=>1,'latitud'=>-12.0621065,'longitud'=>-77.0365256,'categoria_id'=>5,'user_id_comprador'=>2,'condicion'=>'Nuevo','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Mazo de platano','descripcion'=>'Maso hecho de oro 100% oro','precio_inicial'=>90.0,'image_name1'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name2'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name3'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name4'=>'http://imgfz.com/i/bEdwRlf.jpeg','estado'=>'Comprado','inicio_subasta'=>'2020-11-12 10:17:00','final_subasta'=>'2021-12-20 20:47:00','user_id'=>1,'categoria_id'=>5,'user_id_comprador'=>2,'condicion'=>'Nuevo','latitud'=>-12.59254,'longitud'=>-69.188191,'ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);


        DB::table('productos')->insert(['nombre_producto'=>'PlayStation','descripcion'=>'Libro original de Servantes, lo vendo porque necesito espacio en mi casa','precio_inicial'=>100.2,'image_name1'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name2'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name3'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name4'=>'http://imgfz.com/i/bEdwRlf.jpeg','estado'=>'Comprado','inicio_subasta'=>'2020-11-5 20:47:00','final_subasta'=>'2021-11-10 20:47:00','user_id'=>2,'categoria_id'=>1,'latitud'=>-10.666344,'longitud'=>-76.255141,'user_id_comprador'=>1,'condicion'=>'Usado','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Arte rupestre','descripcion'=>'Cuadro de picaso, lo tengo porque soy familiar de picaso 100% seguro, fijense en las imagenes','precio_inicial'=>150.2,'image_name1'=>'http://imgfz.com/i/ghJeXZQ.jpeg','image_name2'=>'http://imgfz.com/i/ghJeXZQ.jpeg','image_name3'=>'http://imgfz.com/i/ghJeXZQ.jpeg','image_name4'=>'http://imgfz.com/i/ghJeXZQ.jpeg','estado'=>'Disponible','inicio_subasta'=>'2020-11-25 18:47:00','final_subasta'=>'2021-12-15 23:47:00','user_id'=>1,'latitud'=>-5.195464,'longitud'=>-80.630873,'categoria_id'=>1,'user_id_comprador'=>2,'condicion'=>'Nuevo','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Telefono Sony','descripcion'=>'Maso hecho de oro 100% oro','precio_inicial'=>82.0,'image_name1'=>'http://imgfz.com/i/6baLGPT.jpeg','image_name2'=>'http://imgfz.com/i/6baLGPT.jpeg','image_name3'=>'http://imgfz.com/i/6baLGPT.jpeg','image_name4'=>'http://imgfz.com/i/6baLGPT.jpeg','estado'=>'No disponible','user_id'=>1,'categoria_id'=>2,'latitud'=>-6.488505,'longitud'=>-76.359318,'user_id_comprador'=>2,'condicion'=>'Usado','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Libro de cocina','descripcion'=>'Libro original de Servantes, lo vendo porque necesito espacio en mi casa','precio_inicial'=>100.2,'image_name1'=>'http://imgfz.com/i/uGhDcmr.jpeg','image_name2'=>'http://imgfz.com/i/uGhDcmr.jpeg','image_name3'=>'http://imgfz.com/i/uGhDcmr.jpeg','image_name4'=>'http://imgfz.com/i/uGhDcmr.jpeg','estado'=>'Disponible','inicio_subasta'=>'2020-11-25 20:47:00','final_subasta'=>'2021-12-19 22:47:00','user_id'=>2,'categoria_id'=>2,'latitud'=>-3.565364,'longitud'=>-80.456874,'user_id_comprador'=>2,'condicion'=>'Nuevo','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Almohadones','descripcion'=>'Cuadro de picaso, lo tengo porque soy familiar de picaso 100% seguro, fijense en las imagenes','precio_inicial'=>30.2,'image_name1'=>'http://imgfz.com/i/WVCnYNe.jpeg','image_name2'=>'http://imgfz.com/i/WVCnYNe.jpeg','image_name3'=>'http://imgfz.com/i/WVCnYNe.jpeg','image_name4'=>'http://imgfz.com/i/WVCnYNe.jpeg','estado'=>'En curso','inicio_subasta'=>'2020-12-12 20:47:00','final_subasta'=>'2021-12-30 18:30:00','latitud'=>-8.383393,'longitud'=>-74.538623,'user_id'=>1,'categoria_id'=>3,'user_id_comprador'=>2,'condicion'=>'Nuevo','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Copa de 1960','descripcion'=>'Maso hecho de oro 100% oro','precio_inicial'=>70.0,'image_name1'=>'http://imgfz.com/i/g7Alfst.jpeg','image_name2'=>'http://imgfz.com/i/g7Alfst.jpeg','image_name3'=>'http://imgfz.com/i/g7Alfst.jpeg','image_name4'=>'http://imgfz.com/i/g7Alfst.jpeg','estado'=>'En curso','inicio_subasta'=>'2020-12-22 20:47:00','final_subasta'=>'2021-12-21 20:55:00','user_id'=>1,'categoria_id'=>3,'user_id_comprador'=>2,'condicion'=>'Nuevo','latitud'=>-8.383393,'longitud'=>-70.31313,'ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Radio estereo','descripcion'=>'Libro original de Servantes, lo vendo porque necesito espacio en mi casa','precio_inicial'=>400.2,'image_name1'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name2'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name3'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name4'=>'http://imgfz.com/i/bEdwRlf.jpeg','estado'=>'En curso','inicio_subasta'=>'2020-11-21 20:47:20','final_subasta'=>'2021-12-6 20:17:10','user_id'=>2,'categoria_id'=>4,'latitud'=>-8.383393,'longitud'=>-70.31313,'user_id_comprador'=>2,'condicion'=>'Usado','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Horno microhondas','descripcion'=>'Maso hecho de oro 100% oro','precio_inicial'=>190.0,'image_name1'=>'http://imgfz.com/i/vrnLG64.jpeg','image_name2'=>'http://imgfz.com/i/vrnLG64.jpeg','image_name3'=>'http://imgfz.com/i/vrnLG64.jpeg','image_name4'=>'http://imgfz.com/i/vrnLG64.jpeg','estado'=>'En curso','inicio_subasta'=>'2020-12-10 20:47:00','final_subasta'=>'2021-12-16 20:33:00','user_id'=>1,'categoria_id'=>4,'user_id_comprador'=>3,'user_id_comprador'=>2,'latitud'=>-7.2342,'longitud'=>-70.31313,'condicion'=>'Nuevo','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Maquina de ejercicio','descripcion'=>'Libro original de Servantes, lo vendo porque necesito espacio en mi casa','precio_inicial'=>20.2,'image_name1'=>'http://imgfz.com/i/Qvz10x7.png','image_name2'=>'http://imgfz.com/i/Qvz10x7.png','image_name3'=>'http://imgfz.com/i/Qvz10x7.png','image_name4'=>'http://imgfz.com/i/Qvz10x7.png','estado'=>'En curso','inicio_subasta'=>'2020-11-27 20:30:00','final_subasta'=>'2021-12-30 20:47:00','user_id'=>2,'categoria_id'=>5,'latitud'=>-7.2342,'longitud'=>-70.31313,'user_id_comprador'=>2,'condicion'=>'Nuevo','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);

        DB::table('productos')->insert(['nombre_producto'=>'Ropero','descripcion'=>'Ropero, lo tengo porque soy familiar de picaso 100% seguro, fijense en las imagenes','precio_inicial'=>30.2,'image_name1'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name2'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name3'=>'http://imgfz.com/i/bEdwRlf.jpeg','image_name4'=>'http://imgfz.com/i/bEdwRlf.jpeg','estado'=>'Comprado','inicio_subasta'=>'2020-12-25 20:47:00','final_subasta'=>'2021-12-19 20:47:00','user_id'=>1,'categoria_id'=>5,'latitud'=>-7.2342,'longitud'=>-70.31313,'user_id_comprador'=>2,'condicion'=>'Nuevo','ubicacion'=>'Lima','distrito'=>'Comas','garantia'=>'No tiene garantía']);



    }
}
